version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    mem_limit: 3072m
    cpus: 0.25
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 5s     
      timeout: 5s     
      retries: 5       
      start_period: 10s 

  redis:
    image: redis:8.0.2
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
      
  test:
    image: my-express-app:dev 
    build:
      context: .
    container_name: app_test
    working_dir: /app 
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm test"
    depends_on:   
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MODE=test
      - POSTGRES_DB=test
      - JWT_KEY=qrqrqr
      - PRIVATE_KEY={"project_id":"mockado"}
      - BUCKET_NAME="lorem ipstu"
    tty: true



volumes:
  postgres_data:
  redis-data:
