version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 256m
    cpus: 0.25
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 5s     
      timeout: 5s     
      retries: 5       
      start_period: 10s 


  api:
    image: my-express-app:dev 
    build:
      context: .
    container_name: app_type1
    ports:
      - "8080:8080"
    working_dir: /app 
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm start"
    cpus: 0.50
    mem_limit: 512m
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      - MODE=development
      - POSTGRES_DB=market


  test:
    image: my-express-app:dev 
    build:
      context: .
    container_name: app_test
    working_dir: /app 
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm test"
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      - MODE=test
      - POSTGRES_DB=test
      - JWT_KEY=qrqrqr
      - PRIVATE_KEY={"project_id":"mockado"}
      - BUCKET_NAME="lorem ipstu"
    tty: true



volumes:
  postgres_data:
