const route = require('express').Router()
const cart = require('./UserCart')
const loginAndRegister = require('./LoginAndRegister')
const products = require('./products')
const stores = require('./stores')
const tickets = require('./tickets')
const reviews = require('./Reviews')
route
.use(loginAndRegister)
.use(products)
.use('/cart',cart)
.use(stores)
.use(tickets)
.use(reviews)
module.exports = route