const route = require('express').Router()
const cart = require('./UserCart')
const loginAndRegister = require('./LoginAndRegister')
const products = require('./products')
const stores = require('./stores')
const tickets = require('./tickets')
const reviews = require('./Reviews')

route.use(loginAndRegister)
route.use(products)
route.use('/cart',cart)
route.use(stores)
route.use(tickets)
route.use(reviews)
module.exports = route