version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_server
    ports:
      - 3309:3309
    environment:
      MYSQL_ROOT_PASSWORD: Nova_Senha@123
      MYSQL_DATABASE: project
  
  node:
    image: node:20-alpine
    container_name: srv_node
    working_dir: /app
    command: sh -c "yarn install  && yarn start"
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Nova_Senha@123
      MYSQL_DATABASE: project
